# Generated by Django 4.1.5 on 2023-02-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=50)),
                ('api_id', models.CharField(blank=True, max_length=250)),
                ('coin_symbol', models.CharField(blank=True, max_length=10)),
                ('categories', models.CharField(blank=True, max_length=250)),
                ('coin_usd', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('website', models.CharField(blank=True, max_length=250)),
                ('coin_change', models.FloatField(default=0.0)),
                ('coin_mcap', models.FloatField(default=0.0)),
                ('market_cap_rank', models.IntegerField(default=0)),
                ('coin_ath_percent', models.FloatField(default=0.0)),
                ('coin_ath', models.FloatField(default=0.0)),
                ('coin_ath_date', models.DateField(blank=True, null=True)),
                ('coin_image', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ('coin_name',),
            },
        ),
    ]
