# Generated by Django 4.1.5 on 2023-02-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ('coinname',)},
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='api_id',
            new_name='apiid',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_ath',
            new_name='coinath',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_ath_date',
            new_name='coinathdate',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_ath_percent',
            new_name='coinathpercent',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_change',
            new_name='coinchange',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_image',
            new_name='coinimage',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_mcap',
            new_name='coinmcap',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_name',
            new_name='coinname',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_symbol',
            new_name='coinsymbol',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_usd',
            new_name='coinusd',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='market_cap_rank',
            new_name='marketcaprank',
        ),
    ]
