# Generated by Django 4.1.5 on 2023-02-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_coin_options_rename_coinname_coin_coin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='coinath',
            new_name='coin_ath',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coinathdate',
            new_name='coin_ath_date',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coinathpercent',
            new_name='coin_ath_percent',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coinchange',
            new_name='coin_change',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coinimage',
            new_name='coin_image',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coinmcap',
            new_name='coin_mcap',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coinsymbol',
            new_name='coin_symbol',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coinusd',
            new_name='coin_usd',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='marketcaprank',
            new_name='marketcap_rank',
        ),
    ]
