# Generated by Django 4.1.5 on 2023-02-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_user_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_coin',
            name='status',
            field=models.CharField(choices=[('R', 'Researching'), ('O', 'Holding'), ('S', 'Sold'), ('O', 'Other')], default='R', max_length=1),
        ),
    ]
