# Generated by Django 4.1.5 on 2023-02-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_user_coin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('E', 'Exchange'), ('W', 'Wallet'), ('O', 'Other')], default='E', max_length=1)),
                ('location_name', models.CharField(blank=True, max_length=50)),
                ('self_custody', models.BooleanField(default=False)),
                ('quantity', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('cost_basis', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('user_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user_coin')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
