# Generated by Django 4.1.5 on 2023-02-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_holding_exchange_holding_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='date',
            field=models.DateField(verbose_name='Holding Date'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='self_custody',
            field=models.CharField(choices=[('C', 'Custodial'), ('S', 'Self'), ('T', 'Smart Contract'), ('O', 'Other')], default='C', max_length=1),
        ),
    ]
