# Generated by Django 4.1.5 on 2023-02-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_user_coin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, max_length=250)),
                ('category_name', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='coin',
            name='categories',
        ),
        migrations.AddField(
            model_name='coin',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main_app.categories'),
        ),
    ]
