# Generated by Django 4.1.5 on 2023-02-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_categories_remove_coin_categories_coin_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='genesis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='hashing_algorithm',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
