# Generated by Django 4.1.5 on 2023-02-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_coin_coin_atl_coin_coin_atl_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
