# Generated by Django 4.1.5 on 2023-02-12 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0017_alter_coin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(blank=True, max_length=500)),
                ('buy_up_to', models.FloatField(default=0.0)),
                ('origin', models.CharField(blank=True, max_length=50)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Note Date')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True, max_length=2500)),
                ('recommendation', models.TextField(choices=[('B', 'Buy'), ('S', 'Self'), ('H', 'Hold'), ('O', 'Other')], default='B', max_length=1)),
                ('Recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recommendation')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
