# Generated by Django 4.1.5 on 2023-02-12 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_coin_last_updated_recommendation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Recommendation Date'),
            preserve_default=False,
        ),
    ]
