# Generated by Django 4.1.5 on 2023-02-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_recommendation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='coin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.coin'),
        ),
    ]
