# Generated by Django 4.1.5 on 2023-02-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_note_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='coin',
        ),
    ]
