# Generated by Django 4.1.5 on 2023-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_note_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
