# Generated by Django 4.1.7 on 2023-11-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_recommendation_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_name',
            field=models.CharField(max_length=100),
        ),
    ]
