# Generated by Django 4.1.7 on 2023-11-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_alter_holding_exchange_alter_holding_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='category_id',
        ),
    ]
